# Configurations
title:            JBNU Applied AI Lab Entrance Page
longtitle:        JBNU Applied AI Lab Entrance Page
author:           Joonseo Hyeon
email:            hjs40111@gmail.com
description: >
  전북대학교 적응형 인공지능 연구실(Applied AI Lab)에 새로 들어온 분들을 위한 페이지입니다.

version:          1.0
gitbook_version:  3.2.3

url:              'https://indigo-coder-github.github.io'
baseurl:          '/applied_AI_lab_entrance'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:title

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  posts:
    output: true
    permalink: /:categories/:title

page_width: 800px

sidebar:
  enabled: true
  width: 300px
  position: left

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - lunr
  - search
  - search-pro
