# Configurations
title:            JBNU Applied AI Lab Entrance
longtitle:        JBNU Applied AI Lab Entrance
author:           Joonseo Hyeon
email:            hjs40111@gmail.com
description: >
  전북대학교 적응형 인공지능 연구실 지식 아카이브입니다.

version:          1.0
gitbook_version:  3.2.3

url:              'https://github.com/Indigo-Coder-github'
baseurl:          '/applied_AI_lab_entrance'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:collection/:path

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  machine_learning:
    output: true
    permalink: /:collection/:path
  deep_learning:
    output: true
    permalink: /:collection/:path
  code:
    output: true
    permalink: /:collection/:path
  etc:
    output: true
    permalink: /:collection/:path

ordered_collections:
  - machine_learning
  - deep_learning
  - code
  - etc

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji